name: Update Countdown

on:
  schedule:
    - cron: '0 0 * * *'  # Si aggiorna ogni giorno a mezzanotte
  workflow_dispatch:  # Permette di eseguirlo manualmente

jobs:
  update-countdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Calcola giorni rimanenti
        id: calc
        run: |
          TARGET="2025-06-24"
          TODAY=$(date +'%Y-%m-%d')
          DAYS=$(( ($(date -d "$TARGET" +%s) - $(date -d "$TODAY" +%s)) / 86400 ))
          echo "days=$DAYS" > countdown.json
          
      - name: Aggiorna il gist
        uses: popsiclestick/gist-sync-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/YOUR_USERNAME/YOUR_GIST_ID
          gist_title: Giorni al 24 giugno
          github_file: countdown.json
